### ISSUE TITLE
Cannot resolve module 'babel-runtime/core-js/promise' 

### ISSUE THREAD

**Issue by jwulf** [JaxCavalera/Tagged#1]
1. Check out repo
2. `npm  install`
3. `npm start`

result:

ERROR in ./app/promise-bootstrap.js
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/promise' in /Users/jwulf/workspace/Tagged/app
 @ ./app/promise-bootstrap.js 3:0-40

**Comment by jwulf** [comment]
Also:

ERROR in ./app/actions/auth-actions.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../constvars.jsx in /Users/jwulf/workspace/Tagged/app/actions
 @ ./app/actions/auth-actions.jsx 22:20-47

**Comment by JaxCavalera** [comment]
I have adjusted the repository to include both the babel etc modules inside the dependencies so they should be installed when running npm install for the repo now.  I have also included constvars.  Typically as constvars.jsx is representing a custom variation on a dotenv file to demonstrate an understanding of how environment variables function without using a management library it is added to the ignore list.  However I'll include it since this is not a standard and the standard usage of .env files can be seen in both the Tagged-Isomorphic and Tagged-DBServer repositories.
